# Use the official Node.js image with version 20.12.2 as the base image
FROM node:20.12.2-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install Python and necessary dependencies
RUN apk add --no-cache python3 py3-pip gcc musl-dev libffi-dev

# Create a virtual environment for Python dependencies within the app directory
RUN python3 -m venv /app/venv

# Activate virtual environment and install the google-cloud-secret-manager package
RUN /app/venv/bin/pip install google-cloud-secret-manager

# Ensure the virtual environment is activated for subsequent commands
ENV PATH="/app/venv/bin:$PATH"

# Fetch the secret from Secret Manager and save it to the correct location
RUN python -c "from google.cloud import secretmanager; \
client = secretmanager.SecretManagerServiceClient(); \
name = 'projects/sigeti/secrets/sigeti-credentials/versions/latest'; \
response = client.access_secret_version(request={'name': name}); \
with open('/app/sigeti-ca02d3a77e56.json', 'wb') as f:\
    f.write(response.payload.data)"

# Set environment variables
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/sigeti-ca02d3a77e56.json

# Build the Next.js application
RUN npm run build

# Expose the port Next.js will run on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]
